// Generated by scripts/build-browser-security.mjs; do not edit.
export const browserSecurityHeaders = {
  "Content-Security-Policy": "default-src 'self'; script-src 'self' 'sha256-+ZQDoHaXrz8V1qxlvZEpqOBm5NZCTBuCIf7k4/IDk6E=' 'sha256-1sy8cwicTQBlN+rYdtmqHj0d/TWf7K1BqCG38jZeie4=' 'sha256-B4C6BBw3l9KLjSXm/NzlzOc4hnxQQvA7ko353/bkGH4=' 'sha256-F1IIZC/LuTrFzA9PCY3LvwEHQYtscw7GW09lFRNdovc=' 'sha256-MF/Bd4SD9ZQcQgGTMRWTnGqeGEcKWNwffcT01H3qnVQ=' 'sha256-ykGiYkjTtdnim9u9MAQ4z0ivSBsKFPdO6993y/aQKaU='; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; img-src 'self' data: blob: https:; media-src 'self' blob:; connect-src 'self' https: wss: http://localhost:* http://127.0.0.1:*; worker-src 'self' blob:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'",
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "DENY",
  "Referrer-Policy": "strict-origin-when-cross-origin"
};
