"""Generate catalogue years directly from the shipped observation manifests."""
import json
from annual_snapshot import DATA, ROOT

years = {}
for path in sorted(DATA.glob('japan-*.json')):
    data = json.loads(path.read_text(encoding='utf-8'))
    if 'periods' in data and data.get('schemaVersion') in [1, 2] and all(isinstance(p.get('year'), int) for p in data['periods']):
        years[path.name] = [p['year'] for p in data['periods']]
target = ROOT / 'src/exploration/annual-observation-years.js'
target.write_text('// Generated by scripts/build-annual-observation-index.py; no invented years.\nexport const ANNUAL_OBSERVATION_YEARS = Object.freeze(' + json.dumps(years, separators=(',', ':')) + ');\n', encoding='utf-8')
